### ISSUE TITLE
重载和重写有什么区别

### ISSUE THREAD

**Issue by Stone-Fly** [Snailclimb/JavaGuide-Interview#24]
文中说到，如果父类方法修饰符为 private/final/static，则子类就不能重写该方法，但是被static修饰的方法能够被再次声明。

但是当我使用下面这个测试代码时，子类中重写了setStr方法，程序并未报错，并且也可以运行，或者说被private修饰的方法，也能够再次被声明？
`
public class Dad {
    public String str;

    private void setStr(String str) {
        this.str = str;
    }
}

public class Son extends Dad {

    public void setStr(String str) {
        this.str = str;
    }

}
`

**Comment by Snailclimb** [comment]
> 如果父类方法修饰符为 private/final/static，则子类就不能重写该方法

https://www.cnblogs.com/xpeanut/p/12811318.html

**Comment by Stone-Fly** [comment]
> > 如果父类方法修饰符为 private/final/static，则子类就不能重写该方法
> 
> https://www.cnblogs.com/xpeanut/p/12811318.html

你这个博文跟我说的不是一个东西啊，static修饰的我知道，我意思是private修饰的也可以这样
