### ISSUE TITLE
2.3.11 synchronized 关键字 中双重校验锁实现对象单例（线程安全）代码方法多了个synchronized 

### ISSUE THREAD

**Issue by 55juekun** [Snailclimb/JavaGuide-Interview#7]
public synchronized static Singleton getUniqueInstance() {} 
getUniqueInstance方法如果已经使用了synchronized 修饰，那么后续的双重校验锁就没有用了吧。应该是方法本身不加synchronized 修饰，但在内部使用synchronized 双重修饰吧。

**Comment by Snailclimb** [comment]
> public synchronized static Singleton getUniqueInstance() {}
> getUniqueInstance方法如果已经使用了synchronized 修饰，那么后续的双重校验锁就没有用了吧。应该是方法本身不加synchronized 修饰，但在内部使用synchronized 双重修饰吧。

已修改。
